spring:
    application:
        name: user-service
    datasource:
        url: jdbc:mysql://175.178.152.16:3306/user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 018418
#        druid:
#            initial-size: 5
#            min-idle: 5
#            max-active: 20
#            max-wait: 60000
#            time-between-eviction-runs-millis: 60000
#            min-evictable-idle-time-millis: 300000
#            validation-query: SELECT 1 FROM DUAL
#            test-while-idle: true
#            test-on-borrow: false
#            test-on-return: false
#            pool-prepared-statements: true
#            max-pool-prepared-statement-per-connection-size: 20
#            filters: stat,wall,log4j
#            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

feign:
    client:
        config:
            default:
                connectTimeout: 10000 #ms
                readTimeout: 60000 #ms

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

server:
    port: 8081

mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

