spring:
    application:
        name: user-service
    datasource:
        url: jdbc:mysql://175.178.152.16:3306/user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 018418

feign:
    client:
        config:
            default:
                connectTimeout: 10000 #ms
                readTimeout: 60000 #ms

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

server:
    port: 8080

mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

