spring:
  application:
    name: article-service
  datasource:
    url: jdbc:mysql://175.178.152.16:3306/platform?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 018418
  rabbitmq:
    host: 175.178.152.16
    port: 5672
    username: guest
    password: guest

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #ms
        readTimeout: 60000 #ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

