spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: service-route
          uri: lb://article-service
          predicates:
            - Path=/api/article/**
        - id: service-route
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 80
